[tool.poetry]
name = "poetry-create-pkg-version"
version = "0.1.0"
description = ""
authors = ["Justin Vrana <justin.vrana@gmail.com>"]
packages = [
    {include = "poetry_create_pkg_version", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"

[tool.poetry.scripts]
poetry-version-up = 'poetry_create_pkg_version.hook:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
