# __version__.py
# autogenerated by poetry-create-pkg-version 0.1.0

__version__ = "0.1.0"
__title__ = "poetry-create-pkg-version"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repository__ = ""
__homepage__ = ""
__description__ = ""
__maintainers__ = ""
__readme__ = ""
__license__ = ""
