# __version__.py
# autogenerated by keats 0.2.28
__version__ = "0.4.0"
__name__ = "poetry-hooks"
__title__ = "poetry-hooks"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repo__ = None
__homepage__ = None
__description__ = ""
