# __version__.py
# autogenerated by poetry-hooks 0.4.2

__version__ = '0.4.2'
__title__ = 'poetry-hooks'
__authors__ = ['Justin Vrana <justin.vrana@gmail.com>']
__repository__ = ''
__homepage__ = ''
__description__ = ''
__maintainers__ = ''
__readme__ = ''
__license__ = ''

